language: php
php:
  - 5.5
  - 5.4
install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer install
script:
  - mkdir -p build/logs
  - phpcs --standard=psr2 src
  - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - bin/coveralls